# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Server

# Model Form Field configuration
form: $/keios/telekinesis/models/server/fields.yaml

# Model Class name
modelClass: Keios\Telekinesis\Models\Server

# Default redirect location
defaultRedirect: keios/telekinesis/servers

# Create page
create:
    title: Create Server
    redirect: keios/telekinesis/servers/update/:id
    redirectClose: keios/telekinesis/servers

# Update page
update:
    title: Edit Server
    redirect: keios/telekinesis/servers
    redirectClose: keios/telekinesis/servers

# Preview page
preview:
    title: Preview Server